export const ACCOMODATION_LIST_REQUEST = 'ACCOMODATION_LIST_REQUEST';
export const ACCOMODATION_LIST_SUCCESS = 'ACCOMODATION_LIST_SUCCESS';
export const ACCOMODATION_LIST_FAIL = 'ACCOMODATION_LIST_FAIL';

export const ACCOMODATION_DETAILS_REQUEST = 'ACCOMODATION_DETAILS_REQUEST';
export const ACCOMODATION_DETAILS_SUCCESS = 'ACCOMODATION_DETAILS_SUCCESS';
export const ACCOMODATION_DETAILS_FAIL = 'ACCOMODATION_DETAILS_FAIL';
export const ACCOMODATION_DETAILS_RESET = 'ACCOMODATION_DETAILS_RESET';

export const ACCOMODATION_DELETE_REQUEST = 'ACCOMODATION_DELETE_REQUEST';
export const ACCOMODATION_DELETE_SUCCESS = 'ACCOMODATION_DELETE_SUCCESS';
export const ACCOMODATION_DELETE_FAIL = 'ACCOMODATION_DELETE_FAIL';

export const ACCOMODATION_CREATE_REQUEST = 'ACCOMODATION_CREATE_REQUEST';
export const ACCOMODATION_CREATE_SUCCESS = 'ACCOMODATION_CREATE_SUCCESS';
export const ACCOMODATION_CREATE_FAIL = 'ACCOMODATION_CREATE_FAIL';
export const ACCOMODATION_CREATE_RESET = 'ACCOMODATION_CREATE_RESET';

export const ACCOMODATION_UPDATE_REQUEST = 'ACCOMODATION_UPDATE_REQUEST';
export const ACCOMODATION_UPDATE_SUCCESS = 'ACCOMODATION_UPDATE_SUCCESS';
export const ACCOMODATION_UPDATE_FAIL = 'ACCOMODATION_UPDATE_FAIL';
export const ACCOMODATION_UPDATE_RESET = 'ACCOMODATION_UPDATE_RESET';
