export const ACCOMMODATION_LIST_REQUEST = 'ACCOMMODATION_LIST_REQUEST';
export const ACCOMMODATION_LIST_SUCCESS = 'ACCOMMODATION_LIST_SUCCESS';
export const ACCOMMODATION_LIST_FAIL = 'ACCOMMODATION_LIST_FAIL';

export const ACCOMMODATION_MY_LIST_REQUEST = 'ACCOMMODATION_MY_LIST_REQUEST';
export const ACCOMMODATION_MY_LIST_SUCCESS = 'ACCOMMODATION_MY_LIST_SUCCESS';
export const ACCOMMODATION_MY_LIST_FAIL = 'ACCOMMODATION_MY_LIST_FAIL';

export const ACCOMMODATION_DETAILS_REQUEST = 'ACCOMMODATION_DETAILS_REQUEST';
export const ACCOMMODATION_DETAILS_SUCCESS = 'ACCOMMODATION_DETAILS_SUCCESS';
export const ACCOMMODATION_DETAILS_FAIL = 'ACCOMMODATION_DETAILS_FAIL';
export const ACCOMMODATION_DETAILS_RESET = 'ACCOMMODATION_DETAILS_RESET';

export const ACCOMMODATION_DELETE_REQUEST = 'ACCOMMODATION_DELETE_REQUEST';
export const ACCOMMODATION_DELETE_SUCCESS = 'ACCOMMODATION_DELETE_SUCCESS';
export const ACCOMMODATION_DELETE_FAIL = 'ACCOMMODATION_DELETE_FAIL';
export const ACCOMMODATION_DELETE_RESET = 'ACCOMMODATION_DELETE_RESET';

export const ACCOMMODATION_CREATE_REQUEST = 'ACCOMMODATION_CREATE_REQUEST';
export const ACCOMMODATION_CREATE_SUCCESS = 'ACCOMMODATION_CREATE_SUCCESS';
export const ACCOMMODATION_CREATE_FAIL = 'ACCOMMODATION_CREATE_FAIL';
export const ACCOMMODATION_CREATE_RESET = 'ACCOMMODATION_CREATE_RESET';

export const ACCOMMODATION_UPDATE_REQUEST = 'ACCOMMODATION_UPDATE_REQUEST';
export const ACCOMMODATION_UPDATE_SUCCESS = 'ACCOMMODATION_UPDATE_SUCCESS';
export const ACCOMMODATION_UPDATE_FAIL = 'ACCOMMODATION_UPDATE_FAIL';
export const ACCOMMODATION_UPDATE_RESET = 'ACCOMMODATION_UPDATE_RESET';

export const ACCOMMODATION_CREATE_REVIEW_REQUEST =
  'ACCOMMODATION_CREATE_REVIEW_REQUEST';
export const ACCOMMODATION_CREATE_REVIEW_SUCCESS =
  'ACCOMMODATION_CREATE_REVIEW_SUCCESS';
export const ACCOMMODATION_CREATE_REVIEW_FAIL =
  'ACCOMMODATION_CREATE_REVIEW_FAIL';
export const ACCOMMODATION_CREATE_REVIEW_RESET =
  'ACCOMMODATION_CREATE_REVIEW_RESET';

export const ACCOMMODATION_TAKEN_REQUEST = 'ACCOMMODATION_TAKEN_REQUEST';
export const ACCOMMODATION_TAKEN_SUCCESS = 'ACCOMMODATION_TAKEN_SUCCESS';
export const ACCOMMODATION_TAKEN_FAIL = 'ACCOMMODATION_TAKEN_FAIL';
