export const ACCOMODATION_LIST_REQUEST = 'ACCOMODATION_LIST_REQUEST';
export const ACCOMODATION_LIST_SUCCESS = 'ACCOMODATION_LIST_SUCCESS';
export const ACCOMODATION_LIST_FAIL = 'ACCOMODATION_LIST_FAIL';

export const ACCOMODATION_DETAILS_REQUEST = 'ACCOMODATION_DETAILS_REQUEST';
export const ACCOMODATION_DETAILS_SUCCESS = 'ACCOMODATION_DETAILS_SUCCESS';
export const ACCOMODATION_DETAILS_FAIL = 'ACCOMODATION_DETAILS_FAIL';
