export const AMENITY_LIST_REQUEST = 'AMENITY_LIST_REQUEST';
export const AMENITY_LIST_SUCCESS = 'AMENITY_LIST_SUCCESS';
export const AMENITY_LIST_FAIL = 'AMENITY_LIST_FAIL';

export const AMENITY_CREATE_REQUEST = 'AMENITY_CREATE_REQUEST';
export const AMENITY_CREATE_SUCCESS = 'AMENITY_CREATE_SUCCESS';
export const AMENITY_CREATE_FAIL = 'AMENITY_CREATE_FAIL';
export const AMENITY_CREATE_RESET = 'AMENITY_CREATE_RESET';

export const AMENITY_DELETE_REQUEST = 'AMENITY_DELETE_REQUEST';
export const AMENITY_DELETE_SUCCESS = 'AMENITY_DELETE_SUCCESS';
export const AMENITY_DELETE_FAIL = 'AMENITY_DELETE_FAIL';
