export const BOOKING_SAVE_PAYMENT_METHOD = 'BOOKING_SAVE_PAYMENT_METHOD';
export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST';
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS';
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL';

export const BOOKING_DETAILS_REQUEST = 'BOOKING_DETAILS_REQUEST';
export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS';
export const BOOKING_DETAILS_FAIL = 'BOOKING_DETAILS_FAIL';

export const BOOKING_PAY_REQUEST = 'BOOKING_PAY_REQUEST';
export const BOOKING_PAY_SUCCESS = 'BOOKING_PAY_SUCCESS';
export const BOOKING_PAY_FAIL = 'BOOKING_PAY_FAIL';
export const BOOKING_PAY_RESET = 'BOOKING_PAY_RESET';

export const BOOKING_MY_LIST_REQUEST = 'BOOKING_MY_LIST_REQUEST';
export const BOOKING_MY_LIST_SUCCESS = 'BOOKING_MY_LIST_SUCCESS';
export const BOOKING_MY_LIST_FAIL = 'BOOKING_MY_LIST_FAIL';
export const BOOKING_MY_LIST_RESET = 'BOOKING_MY_LIST_RESET';

export const BOOKING_LIST_REQUEST = 'BOOKING_LIST_REQUEST';
export const BOOKING_LIST_SUCCESS = 'BOOKING_LIST_SUCCESS';
export const BOOKING_LIST_FAIL = 'BOOKING_LIST_FAIL';
